### ISSUE TITLE
raise OSError('CUDA runtime library not found')

### ISSUE THREAD

**Issue by myplusd** [mxbastidasr/DAWN_WACV2020#11]
hello，Can someone help me
Traceback (most recent call last):
  File "F:\下载\DAWN_WACV2020-master\DAWN_WACV2020-master\models\utils_scat.py", line 9, in <module>
    from skcuda import cublas, cufft
  File "C:\Users\17208\anaconda3\Lib\site-packages\skcuda\cublas.py", line 22, in <module>
    from . import cuda
  File "C:\Users\17208\anaconda3\Lib\site-packages\skcuda\cuda.py", line 9, in <module>
    from .cudart import *
  File "C:\Users\17208\anaconda3\Lib\site-packages\skcuda\cudart.py", line 41, in <module>
    raise OSError('CUDA runtime library not found')
OSError: CUDA runtime library not found
But I've installed the cuda environment，Thank you very much for your answers

**Comment by beltegeuse** [comment]
Hi!

Please ensure that the correct CUDA version is installed. It is common to encounter errors when packages require a specific CUDA version. To avoid this, please refer to the documentation of cublas to confirm which version you need. 

Please be aware that this error is not related to this project, but rather a dependency issue.

**Comment by myplusd** [comment]
thanks
